Repository AstarTeam/hufs_baekjoon_front, pull requests merged in 2023-05, with the labels that each got.

#16 Feat: Select box 와 table data 연결
  src/components/common/selectBox/SelectBox.jsx
  src/components/common/selectBox/selectBox.module.css
  src/components/home/problemList/ProblemList.jsx
  src/utils/problemSort.js
Labels: ✨Feat, ⚔Fix

#17 Feat: 문제 리스트 임시 api 연결
  public/data/problems.json
  src/App.jsx
  src/components/home/problemList/ProblemList.jsx
Labels: ✨Feat, 🚀API

#20 Style: navigate를 Link to로 변경
  src/components/common/header/Header.jsx
  src/components/common/header/header.module.css
Labels: ✨Feat, ⚔Fix

#21 Feat & Fix : 문제 리스트 테이블 링크 연결 및 아이콘 추가
  public/data/problems.json
  src/assets/icons/level/1.svg
  src/assets/icons/level/10.svg
  src/assets/icons/level/11.svg
  src/assets/icons/level/12.svg
  src/assets/icons/level/13.svg
  src/assets/icons/level/14.svg
  src/assets/icons/level/15.svg
  src/assets/icons/level/16.svg
  src/assets/icons/level/17.svg
  src/assets/icons/level/18.svg
  src/assets/icons/level/19.svg
  src/assets/icons/level/2.svg
  src/assets/icons/level/20.svg
  src/assets/icons/level/21.svg
  src/assets/icons/level/22.svg
  src/assets/icons/level/23.svg
  src/assets/icons/level/24.svg
  src/assets/icons/level/25.svg
  src/assets/icons/level/26.svg
  src/assets/icons/level/27.svg
  src/assets/icons/level/28.svg
  src/assets/icons/level/29.svg
  src/assets/icons/level/3.svg
  src/assets/icons/level/30.svg
  src/assets/icons/level/4.svg
  src/assets/icons/level/5.svg
  src/assets/icons/level/6.svg
  src/assets/icons/level/7.svg
  src/assets/icons/level/8.svg
  src/assets/icons/level/9.svg
  src/components/common/paginationBtn/PaginationBtn.jsx
  src/components/common/paginationBtn/paginationBtn.module.css
  src/components/common/table/Table.jsx
  src/components/common/table/table.module.css
  src/components/home/button/Button.jsx
  src/components/home/button/button.module.css
  src/components/home/levelIcon/LevelIcon.jsx
  src/components/home/levelIcon/levelIcon.module.css
  src/components/home/problemList/ProblemList.jsx
Labels: ✨Feat, ⚔Fix

#25 Feat: 문제 리스트 api 연결 및 prefetch 구현
  public/data/problems0.json
  public/data/problems1.json
  src/components/common/loading/Loading.jsx
  src/components/common/loading/loading.module.css
  src/components/home/problemList/ProblemList.jsx
  src/pages/home/Home.jsx
Labels: ✨Feat, 🚀API

#29 Feat: 마이페이지 UI 구현
  src/components/myPage/button/Button.jsx
  src/components/myPage/button/button.module.css
  src/components/myPage/certificateForm/CertificateForm.jsx
  src/components/myPage/certificateForm/certificate.module.css
  src/components/myPage/leftNav/LeftNav.jsx
  src/components/myPage/leftNav/leftNav.module.css
  src/components/myPage/myInfoForm/MyInfoForm.jsx
  src/components/myPage/myInfoForm/myInfoForm.module.css
  src/components/myPage/passwordForm/PasswordForm.jsx
  src/components/myPage/passwordForm/passwordForm.module.css
  src/pages/mypage/Mypage.jsx
  src/pages/mypage/myPage.module.css
Labels: ✨Feat

#30 Feat: 마이페이지 기존 정보 받아오기 및 비밀번호 수정 유효성 검사기능 추가
  public/data/myProfile.json
  src/assets/images/text.txt
  src/components/myPage/myInfoForm/MyInfoForm.jsx
  src/components/myPage/myInfoForm/myInfoForm.module.css
  src/components/myPage/passwordForm/PasswordForm.jsx
  src/components/myPage/passwordForm/passwordForm.module.css
  src/utils/problemSort.js
Labels: ✨Feat, 🚀API

#24 Style: 회원가입 폼 스타일 수정
  src/pages/join/Join.jsx
  src/pages/join/join.module.css
Labels: ✨Feat

#31 Feat: 난수 받아오기 및 백준 아이디, 이미지 post 기능 추가
  public/data/randomNum.json
  src/components/myPage/certificateForm/CertificateForm.jsx
  src/components/myPage/certificateForm/certificate.module.css
Labels: ✨Feat, 🚀API

#32 Feat: 회원가입 중복 및 유효성 검사
  src/pages/join/Join.jsx
Labels: ✨Feat, 🚀API
